'use server'

import {signIn} from "@/auth";
import {AuthError} from "next-auth";

export async function authenticate(prevState: string | undefined, formData: FormData) {
    try {
        await signIn('credentials', formData);
    } catch (e) {
        if(e instanceof AuthError) {
            switch(e.type) {
                case 'CredentialsSignin':
                    return 'Invalid Credentials';
                default:
                    return 'Something went wrong';
            }
        }
    }
}